### ISSUE TITLE
can you please upload the dylib file--- xcode not compatible

### ISSUE THREAD

**Issue by adamsager04** [officialquake/simplicity.cc-quake-paste#1]
xcode is not compatible with my hack can you upload the dylib thnx!

**Comment by ghost** [comment]
> xcode is not compatible with my hack can you upload the dylib thnx!

why not upgrade ur mac to macos mojave eggsdee

**Comment by adamsager04** [comment]
my MacBook can't its kinda old mac os sierra is the highest i can get

**Comment by officialquake** [comment]
you're gonna have to get someone to do it for you. I'm not posting a dylib in github
