### ISSUE TITLE
SDL2/SDL.h not found

### ISSUE THREAD

**Issue by NickTacke** [officialquake/simplicity.cc-quake-paste#3]
The title says it all.
 when I try to build it, it gives me an error that SDL.h is not found.

<img width="689" alt="Screenshot 2019-09-07 at 23 13 30" src="https://user-images.githubusercontent.com/44647382/64480285-30437300-d1c5-11e9-94eb-93bde92c4963.png">

**Comment by ghost** [comment]
`brew install sdl2`
You should install SDL2, and this MacOS cheating source is outdated, you need to update it to be able to make it work.
